# 🐍 Python Data Structures — Complete Study Guide
### Instructor-Curated Notebook | Covers Lists, Sets, Tuples, Dictionaries, Control Flow & NumPy

---

## 📚 Table of Contents
1. [Lists](#1-lists)
2. [Tuples](#2-tuples)
3. [Sets](#3-sets)
4. [Dictionaries](#4-dictionaries)
5. [Differences Among Data Structures](#5-differences)
6. [Applications of Data Structures](#6-applications)
7. [Branching and Control Loops with Data Structures](#7-control-flow)
8. [Matrix Operations Using NumPy](#8-numpy)

---
> **Note to Students:** Run each cell in order. Experiment by changing values and observing outputs. Programming is learned by doing! 💡

---
# 1. LISTS 📋

## What is a List?
A **List** is an **ordered**, **mutable** (changeable), and **indexed** collection of items. 
Lists allow **duplicate** values and can hold items of **different data types** 
(integers, strings, floats, even other lists).

### Key Characteristics:
| Property | Value |
|---|---|
| Ordered | ✅ Yes |
| Mutable | ✅ Yes |
| Allows Duplicates | ✅ Yes |
| Indexed | ✅ Yes (0-based) |
| Syntax | `[ ]` |

---
## 1.1 Creating Lists

In [4]:
# ── Creating Lists ──────────────────────────────────────────────

# Empty list
empty_list = []
print("Empty list:", empty_list)



Empty list: []


In [5]:
# List of integers
numbers = [10, 20, 30, 40, 50]
print("Numbers:", numbers)



Numbers: [10, 20, 30, 40, 50]


In [8]:
std_list=[]
n=int(input("Enter the number of Students: "))
for i in range(n):
    name=input("Enter the name of Student: ")
    std_list.append(name)
print("List of Students:", std_list)
print(type(std_list))

List of Students: ['abc', 'an']
<class 'list'>


In [12]:
# List of strings
fruits = ["apple", "banana", "cherry", "mango"]
print("Fruits:", fruits)

print("Type of fruits variable:", type(fruits[0]))
print("Type of fruits variable:", type(fruits))

Fruits: ['apple', 'banana', 'cherry', 'mango']
Type of fruits variable: <class 'str'>
Type of fruits variable: <class 'list'>


In [13]:
cgps=[8.9,9.0,9.1,7.5]
print("CGPA List:", cgps)

CGPA List: [8.9, 9.0, 9.1, 7.5]


In [16]:
# Mixed data types
mixed = [42, "hello", 3.14, True, None, [1, 2, 3], {12: "raju"},5+6j]
print("Mixed:", mixed)
for i in mixed:
    print(f"Element: {i}, Type: {type(i)}")

Mixed: [42, 'hello', 3.14, True, None, [1, 2, 3], {12: 'raju'}, (5+6j)]
Element: 42, Type: <class 'int'>
Element: hello, Type: <class 'str'>
Element: 3.14, Type: <class 'float'>
Element: True, Type: <class 'bool'>
Element: None, Type: <class 'NoneType'>
Element: [1, 2, 3], Type: <class 'list'>
Element: {12: 'raju'}, Type: <class 'dict'>
Element: (5+6j), Type: <class 'complex'>


In [17]:
# List with duplicates
dupes = [1, 2, 2, 3, 3, 3]
print("With duplicates:", dupes)



With duplicates: [1, 2, 2, 3, 3, 3]


In [ ]:
# Nested list (list inside a list)
nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Nested list:", nested)



In [19]:
# Using list() constructor
from_constructor = list(("a", "b", "c"))
print("From constructor:", from_constructor)
print(type(from_constructor))


From constructor: ['a', 'b', 'c']
<class 'list'>


In [ ]:
# List comprehension (advanced creation)
squares = [x**2 for x in range(1, 6)]
print("Squares via comprehension:", squares)

## 1.2 Accessing List Elements

Lists use **zero-based indexing**. You can also use **negative indexing** to access from the end.

```
 Index:    0      1       2       3
 List:  ["apple", "banana", "cherry", "mango"]
 Neg:     -4      -3       -2       -1
```

In [23]:
# ── Accessing List Elements ──────────────────────────────────────

fruits = ["apple", "banana", "cherry", "mango", "orange"]

# Positive indexing
print("First element  (index 0):", fruits[0])
print("Second element (index 1):", fruits[1])
print("Third element  (index 2):", fruits[2])

print("element at index 3:", fruits[3])

First element  (index 0): apple
Second element (index 1): banana
Third element  (index 2): cherry
element at index 3: mango


In [24]:
# Negative indexing
print("\nLast element    (index -1):", fruits[-1])
print("Second last     (index -2):", fruits[-2])




Last element    (index -1): orange
Second last     (index -2): mango


In [30]:
# Slicing: list[start:stop:step]
print("\n--- Slicing ---")
print(fruits)
print("fruits[1:4]   :", fruits[1:4])   # index 1 to 3
print("fruits[:3]    :", fruits[:3])    # first 3
print("fruits[2:]    :", fruits[2:])    # from index 2 to end
print("fruits[::2]   :", fruits[::2])   # every 2nd element
print("fruits[:4:2]  :", fruits[:4:2])  # from index 0 to 3, every 2nd element
print("fruits[::-1]  :", fruits[::-1])  # reversed




--- Slicing ---
['apple', 'banana', 'cherry', 'mango', 'orange']
fruits[1:4]   : ['banana', 'cherry', 'mango']
fruits[:3]    : ['apple', 'banana', 'cherry']
fruits[2:]    : ['cherry', 'mango', 'orange']
fruits[::2]   : ['apple', 'cherry', 'orange']
fruits[:4:2]  : ['apple', 'cherry']
fruits[::-1]  : ['orange', 'mango', 'cherry', 'banana', 'apple']


In [31]:
# Accessing nested list
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("\nNested list:", matrix)
print("\nNested list element [1][2]:", matrix[1][2])  # row 1, col 2 → 6


Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Nested list element [1][2]: 6


In [32]:
print(matrix[2][:])

[7, 8, 9]


In [33]:
print(matrix[2][0])  # row 2, col 0 → 7

7


## 1.3 All List Methods — Explained

| Method | Description |
|---|---|
| `append(x)` | Adds item `x` at the end |
| `insert(i, x)` | Inserts `x` at index `i` |
| `extend(iterable)` | Adds all items from iterable |
| `remove(x)` | Removes first occurrence of `x` |
| `pop(i)` | Removes & returns item at index `i` (default: last) |
| `clear()` | Removes all items |
| `index(x)` | Returns index of first occurrence of `x` |
| `count(x)` | Returns count of `x` in list |
| `sort()` | Sorts the list in-place |
| `reverse()` | Reverses the list in-place |
| `copy()` | Returns a shallow copy |
| `len(list)` | Returns number of elements (built-in) |

In [43]:
li=[13,22,13]
print(li)
li.append(44)
print(li)
li.insert(1,10)
print(li)

print(li.remove(13))
print(li.pop(0))
print(li)

[13, 22, 13]
[13, 22, 13, 44]
[13, 10, 22, 13, 44]
None
10
[22, 13, 44]


In [ ]:
print(text)

In [47]:
lis=[10,22,13,24,22]
print(lis.index(23))

ValueError: 23 is not in list

In [ ]:
# ── All List Methods Demonstrated ───────────────────────────────

lst = [30, 10, 50, 20, 40, 10]
print("Original:", lst)



In [53]:
lis=[]
n=input("Enter number of elements:")
for i in range(int(n)):
    ele=int(input("Enter Element:"))
    lis.append(ele)
print("List of elements:", lis)


List of elements: [1, 2, 3, 4]


In [64]:
print(lis)
n=int(input("Enter index to insert:"))
ele=int(input("Enter element to insert:"))
lis.insert(n, ele)
print(n)
print(lis)

[1, 2, 3, 123, 2, 1, 4, 12, 123, 123]
8
[1, 2, 3, 123, 2, 1, 4, 12, 2, 123, 123]


In [65]:
print(lis)
n=int(input("Enter value to remove:"))
print("Entered value:", n)
lis.remove(n)
print(lis)

[1, 2, 3, 123, 2, 1, 4, 12, 2, 123, 123]
Entered value: 2
[1, 3, 123, 2, 1, 4, 12, 2, 123, 123]


In [ ]:
lis=[0,1,2,3,4,5,1]
print(lis)
lis.pop(1)
print(lis)
lis.remove(1)
print(lis)

[0, 2, 3, 4, 5, 1]
[0, 3, 4, 5, 1]
[0, 3, 4, 5]


In [68]:
lis=[0,2,3,4,5,1]
print(lis)
lis.pop()
print(lis)
lis.remove(1)
print(lis)

[0, 2, 3, 4, 5, 1]
[0, 2, 3, 4, 5]


ValueError: list.remove(x): x not in list

In [69]:
lis=[10,1,2,3,4,5]
print(lis.pop(0),end=" ")
for i in range(len(lis)):
    print(lis[i],end=" ")

10 1 2 3 4 5 

In [70]:
lis=[10,1,2,3,4,5]
print(lis.remove(10),end=" ")
for i in range(len(lis)):
    print(lis[i],end=" ")

None 1 2 3 4 5 

In [76]:
lis=[10,1,2,3,4,5]
rem=[]
index=0
len_lis=len(lis)
while len(lis):
    l=lis.pop(index)
    index+=1
    rem.append(l)
print(rem)

IndexError: pop index out of range

In [66]:
print(lis)
n=int(input("Enter value to remove:"))
print("Entered value:", n)
while n in lis:
    lis.remove(n)
print(lis)

[1, 3, 123, 2, 1, 4, 12, 2, 123, 123]
Entered value: 2
[1, 3, 123, 1, 4, 12, 123, 123]


In [51]:
ele=int(input("Enter Element:"))

ValueError: invalid literal for int() with base 10: 'a'

In [77]:
# append() — add to end
lst=[0,1,2,3,4,5,1]
lst.append(60)
print("After append(60):", lst)



After append(60): [0, 1, 2, 3, 4, 5, 1, 60]


In [78]:
# insert() — add at position
lst.insert(1, 99)
print("After insert(1, 99):", lst)



After insert(1, 99): [0, 99, 1, 2, 3, 4, 5, 1, 60]


In [79]:
# extend() — merge another list
lst.extend([70, 80])
print("After extend([70,80]):", lst)



After extend([70,80]): [0, 99, 1, 2, 3, 4, 5, 1, 60, 70, 80]


In [82]:
# remove() — remove first occurrence
lst.remove(99)
print("After remove(99):", lst)  # removes only the first 10



After remove(99): [0, 1, 2, 3, 4, 5, 1, 60, 70, 80]


In [83]:
# pop() — remove and return by index
popped = lst.pop(0)
print(f"After pop(0): {lst}  | Popped value: {popped}")



After pop(0): [1, 2, 3, 4, 5, 1, 60, 70, 80]  | Popped value: 0


In [85]:
# index() — find position
idx = lst.index(60)
print("Index of 60:", idx)



Index of 60: 6


In [86]:
# count() — how many times an item appears
print("Count of 1:", lst.count(1))



Count of 1: 2


In [87]:
# sort() — ascending by default
lst.sort()
print("After sort():", lst)



After sort(): [1, 1, 2, 3, 4, 5, 60, 70, 80]


In [88]:
# sort(reverse=True) — descending
lst.sort(reverse=True)
print("After sort(reverse=True):", lst)



After sort(reverse=True): [80, 70, 60, 5, 4, 3, 2, 1, 1]


In [89]:
# reverse() — flip the list
lst.reverse()
print("After reverse():", lst)



After reverse(): [1, 1, 2, 3, 4, 5, 60, 70, 80]


In [94]:
# copy() — shallow copy
copied = lst.copy()
print("Copied list:", copied)
print("Original list:", lst)
lst.pop()
print("After modifying original list:")
print("Original list:", lst)
print("Copied list (unchanged):", copied)


Copied list: [1, 1, 2, 3, 4, 5, 60]
Original list: [1, 1, 2, 3, 4, 5, 60]
After modifying original list:
Original list: [1, 1, 2, 3, 4, 5]
Copied list (unchanged): [1, 1, 2, 3, 4, 5, 60]


In [95]:

copied = lst
print("Copied list:", copied)
print("Original list:", lst)
lst.pop()
print("After modifying original list:")
print("Original list:", lst)
print("Copied list (unchanged):", copied)

Copied list: [1, 1, 2, 3, 4, 5]
Original list: [1, 1, 2, 3, 4, 5]
After modifying original list:
Original list: [1, 1, 2, 3, 4]
Copied list (unchanged): [1, 1, 2, 3, 4]


In [96]:
print("Copied list:", copied)
print("Original list:", lst)
lst.append(70)
print("After modifying original list:")
print("Original list:", lst)
print("Copied list (unchanged):", copied)

Copied list: [1, 1, 2, 3, 4]
Original list: [1, 1, 2, 3, 4]
After modifying original list:
Original list: [1, 1, 2, 3, 4, 70]
Copied list (unchanged): [1, 1, 2, 3, 4, 70]


After modifying original list:
Original list: [1, 1, 2, 3, 4, 5, 60]
Copied list (unchanged): [1, 1, 2, 3, 4, 5, 60]


In [97]:
# len() — number of elements
print("Length:", len(lst))



Length: 6


In [98]:
# clear() — empty the list
lst.clear()
print("After clear():", lst)

After clear(): []


In [ ]:
# insert() — add at position
lst.insert(1, 99)
print("After insert(1, 99):", lst)

# extend() — merge another list
lst.extend([70, 80])
print("After extend([70,80]):", lst)

# remove() — remove first occurrence
lst.remove(10)
print("After remove(10):", lst)  # removes only the first 10

# pop() — remove and return by index
popped = lst.pop(0)
print(f"After pop(0): {lst}  | Popped value: {popped}")

# index() — find position
idx = lst.index(50)
print("Index of 50:", idx)

# count() — how many times an item appears
print("Count of 10:", lst.count(10))

# sort() — ascending by default
lst.sort()
print("After sort():", lst)

# sort(reverse=True) — descending
lst.sort(reverse=True)
print("After sort(reverse=True):", lst)

# reverse() — flip the list
lst.reverse()
print("After reverse():", lst)

# copy() — shallow copy
copied = lst.copy()
print("Copied list:", copied)

# len() — number of elements
print("Length:", len(lst))

# clear() — empty the list
lst.clear()
print("After clear():", lst)

In [99]:
# ── 🎯 Practical Program: Student Grade Manager ──────────────────

print("=" * 45)
print("       STUDENT GRADE MANAGER")
print("=" * 45)

students = ["Alice", "Bob", "Charlie", "Diana", "Eve"]
grades   = [88, 72, 95, 60, 84]

# Display all students and grades
print("\nStudent Roster:")
for i in range(len(students)):
    print(f"  {i+1}. {students[i]:<10} — Grade: {grades[i]}")

# Statistics
avg   = sum(grades) / len(grades)
top   = students[grades.index(max(grades))]
low   = students[grades.index(min(grades))]

print(f"\n📊 Statistics:")
print(f"  Average Grade : {avg:.2f}")
print(f"  Highest Scorer: {top} ({max(grades)})")
print(f"  Lowest  Scorer: {low} ({min(grades)})")

# Add a new student
students.append("Frank")
grades.append(91)
print(f"\n✅ Added Frank with grade 91")

# Sort by grade (descending)
paired = list(zip(grades, students))
paired.sort(reverse=True)
print("\n🏆 Rankings (Highest to Lowest):")
for rank, (g, s) in enumerate(paired, start=1):
    print(f"  #{rank} {s:<10} — {g}")

       STUDENT GRADE MANAGER

Student Roster:
  1. Alice      — Grade: 88
  2. Bob        — Grade: 72
  3. Charlie    — Grade: 95
  4. Diana      — Grade: 60
  5. Eve        — Grade: 84

📊 Statistics:
  Average Grade : 79.80
  Highest Scorer: Charlie (95)
  Lowest  Scorer: Diana (60)

✅ Added Frank with grade 91

🏆 Rankings (Highest to Lowest):
  #1 Charlie    — 95
  #2 Frank      — 91
  #3 Alice      — 88
  #4 Eve        — 84
  #5 Bob        — 72
  #6 Diana      — 60


In [10]:
lis=[10,22,13,24,22]
print(lis)
lis[3]='hai'
print(lis)



[10, 22, 13, 24, 22]
[10, 22, 13, 'hai', 22]


In [12]:
print(lis)
lis[1:4]=[100,'ramu',200]
print(lis)

[10, 100, 200, 'ramu', 22]
[10, 100, 'ramu', 200, 22]


In [ ]:
#list built in method to update a value
s=(10,22,13,24,22)   
print(s)
print(s[3])

(10, 22, 13, 24, 22)
24


In [14]:
s[3]=30

TypeError: 'tuple' object does not support item assignment

---
# 2. TUPLES 📦

## What is a Tuple?
A **Tuple** is an **ordered**, **immutable** (unchangeable), and **indexed** collection. Once created, its elements **cannot be modified**. Tuples are faster than lists and are used to store data that should not change.

### Key Characteristics:
| Property | Value |
|---|---|
| Ordered | ✅ Yes |
| Mutable | ❌ No (Immutable) |
| Allows Duplicates | ✅ Yes |
| Indexed | ✅ Yes |
| Syntax | `( )` |

---
## 2.1 Creating & Accessing Tuples

In [102]:
lis=[1]
print(lis)
liss=[]
print(liss)

[1]
[]


In [106]:
t=()
print(t)
print(type(t))

()
<class 'tuple'>


In [105]:
t=(1)
print(t)
print(type(t))

1
<class 'int'>


In [107]:
t=(1,)
print(t)
print(type(t))

(1,)
<class 'tuple'>


In [108]:
t=(1,2)
print(t)
print(type(t))

(1, 2)
<class 'tuple'>


In [119]:
# ── Creating Tuples ──────────────────────────────────────────────

# Empty tuple
empty_tuple = ()
print("Empty tuple:", empty_tuple)

# Single element tuple — NOTE: trailing comma is REQUIRED!
single = (42,)
not_a_tuple = (42)   # This is just an int!
print("Single element tuple:", single, "| Type:", type(single))
print("Without comma:", not_a_tuple, "| Type:", type(not_a_tuple))

# Regular tuple
coordinates = (10.5, 20.3)
colors = ("red", "green", "blue")
mixed  = (1, "hello", 3.14, True)
print("\nCoordinates:", coordinates)
print("Colors:", colors)
print("Mixed:", mixed)







Empty tuple: ()
Single element tuple: (42,) | Type: <class 'tuple'>
Without comma: 42 | Type: <class 'int'>

Coordinates: (10.5, 20.3)
Colors: ('red', 'green', 'blue')
Mixed: (1, 'hello', 3.14, True)


In [ ]:
# Tuple packing and unpacking

person = ("Alice", 25, "Engineer")    # Packing
name, age, job = person               # Unpacking
print(f"\nUnpacked — Name: {name}, Age: {age}, Job: {job}")


Unpacked — Name: Alice, Age: 25, Job: Engineer


In [115]:
person = ("Alice", 25, "Engineer")    # Packing
name1, age1 = person             # Unpacking
print(f"\nUnpacked — Name: {name1}, Age: {age1}")

ValueError: too many values to unpack (expected 2)

In [116]:
person = ("Alice", 25, "Engineer")    # Packing
name1, age1 = person[0:2]             # Unpacking
print(f"\nUnpacked — Name: {name1}, Age: {age1}")


Unpacked — Name: Alice, Age: 25


In [117]:
# Nested tuple
nested = ((1, 2), (3, 4), (5, 6))
print("Nested tuple:", nested)
print("Access nested[1][0]:", nested[1][0])  # → 3

Nested tuple: ((1, 2), (3, 4), (5, 6))
Access nested[1][0]: 3


In [120]:
# ── Accessing ────────────────────────────────────────────────────
print("\n--- Accessing ---")
print("colors[0]  :", colors[0])
print("colors[-1] :", colors[-1])
print("colors[0:2]:", colors[0:2])   # slicing works!


--- Accessing ---
colors[0]  : red
colors[-1] : blue
colors[0:2]: ('red', 'green')


## 2.2 Tuple Methods

Tuples are immutable, so they have **only 2 built-in methods**:

| Method | Description |
|---|---|
| `count(x)` | Returns how many times `x` appears |
| `index(x)` | Returns index of first occurrence of `x` |

Additionally, these **built-in functions** work on tuples:

| Function | Description |
|---|---|
| `len(t)` | Number of elements |
| `min(t)` | Minimum value |
| `max(t)` | Maximum value |
| `sum(t)` | Sum of all elements |
| `sorted(t)` | Returns a sorted list (doesn't modify tuple) |

In [121]:
l=[1,2,3]
max(l)

3

In [123]:
sum(l)

6

In [122]:
t=(15,25,10)
max(t)

25

In [124]:
sum(t)

50

In [125]:
sorted(t)

[10, 15, 25]

In [ ]:
# ── Tuple Methods Demonstrated ───────────────────────────────────

t = (5, 3, 8, 1, 3, 7, 3, 9, 2)
print("Tuple:", t)

# count()
print("count(3)  :", t.count(3))    # 3 appears 3 times

# index()
print("index(8)  :", t.index(8))    # position of 8

# Built-in functions
print("len()     :", len(t))
print("min()     :", min(t))
print("max()     :", max(t))
print("sum()     :", sum(t))
print("sorted()  :", sorted(t))     # returns a list, tuple unchanged

# Concatenation and repetition (creates new tuple)
t2 = (10, 20)
print("\nConcatenation:", t2 + (30, 40))
print("Repetition   :", t2 * 3)

# Membership test
print("\n8 in t :", 8 in t)
print("99 in t:", 99 in t)

# Converting between list and tuple
as_list  = list(t)
as_tuple = tuple(as_list)
print("\nAs list :", as_list)
print("Back to tuple:", as_tuple)

In [ ]:
# ── 🎯 Practical Program: GPS Coordinate Tracker ─────────────────

print("=" * 45)
print("       GPS COORDINATE TRACKER")
print("=" * 45)

# Storing locations as tuples (immutable — coordinates don't change!)
locations = {
    "Home"      : (17.3850, 78.4867),
    "College"   : (17.4400, 78.4983),
    "Hospital"  : (17.3616, 78.4747),
    "Airport"   : (17.2403, 78.4294),
}

import math

def distance(loc1, loc2):
    """Approximate distance in km between two lat/lon points."""
    lat1, lon1 = loc1
    lat2, lon2 = loc2
    return math.sqrt((lat2 - lat1)**2 + (lon2 - lon1)**2) * 111

print("\n📍 Saved Locations:")
for name, coords in locations.items():
    lat, lon = coords   # tuple unpacking
    print(f"  {name:<12}: Lat={lat}, Lon={lon}")

home = locations["Home"]
print("\n📏 Distances from Home:")
for name, coords in locations.items():
    if name != "Home":
        d = distance(home, coords)
        print(f"  Home → {name:<12}: {d:.2f} km")

---
# 3. SETS 🔵

## What is a Set?
A **Set** is an **unordered**, **mutable**, collection of **unique** elements. Sets do **not allow duplicates** and have **no index**. They are ideal for membership testing and eliminating duplicates.

### Key Characteristics:
| Property | Value |
|---|---|
| Ordered | ❌ No |
| Mutable | ✅ Yes |
| Allows Duplicates | ❌ No |
| Indexed | ❌ No |
| Syntax | `{ }` |

---
## 3.1 Creating & Accessing Sets

In [15]:
# ── Creating Sets ────────────────────────────────────────────────

# Empty set — MUST use set(), not {} (that creates a dict!)
empty_set = set()
print("Empty set:", empty_set, "| Type:", type(empty_set))



Empty set: set() | Type: <class 'set'>


In [20]:
l=[]
s=(2.2,)
se=set()
print(type(l))
print(type(s))
print(type(se))

<class 'list'>
<class 'tuple'>
<class 'set'>


In [22]:
# Creating with values
fruits = {"apple", "banana", "cherry", "mango"}
print("Fruits:", fruits)
lis=[10,20,12]
print(lis)
t=(23,12,222)
print(t)

Fruits: {'banana', 'mango', 'cherry', 'apple'}
[10, 20, 12]
(23, 12, 222)


In [24]:
# Duplicates are automatically removed!
with_dupes = {1, 3, 3, 3, 4,2,2}
print("With duplicates input → Set:", with_dupes)  # only unique values



With duplicates input → Set: {1, 2, 3, 4}


In [26]:
# From list (great way to remove duplicates)
my_list = [10, 20, 20, 30, 10, 40]
unique_set = set(my_list)
print("Set from list:", unique_set)
lis=list(unique_set)
print(lis)



Set from list: {40, 10, 20, 30}
[40, 10, 20, 30]


In [27]:
# Membership test (very fast!)
print("\n'apple' in fruits:", "apple" in fruits)
print("'grape' in fruits:", "grape" in fruits)


'apple' in fruits: True
'grape' in fruits: False


## 3.2 All Set Methods — Explained

### Modification Methods:
| Method | Description |
|---|---|
| `add(x)` | Adds element `x` |
| `update(iterable)` | Adds multiple elements |
| `remove(x)` | Removes `x`; raises error if not found |
| `discard(x)` | Removes `x`; no error if not found |
| `pop()` | Removes and returns an arbitrary element |
| `clear()` | Removes all elements |

### Set Operations (Mathematical):
| Method | Operator | Description |
|---|---|---|
| `union(s)` | `\|` | All elements from both sets |
| `intersection(s)` | `&` | Elements common to both |
| `difference(s)` | `-` | Elements in first but not second |
| `symmetric_difference(s)` | `^` | Elements in either but not both |
| `issubset(s)` | `<=` | Is this set a subset? |
| `issuperset(s)` | `>=` | Is this set a superset? |
| `isdisjoint(s)` | — | Do sets share no elements? |

In [44]:
# ── Set Methods Demonstrated ─────────────────────────────────────

s = {10, 20, 30, 40, 50}
print("Original set:", s)



Original set: {50, 20, 40, 10, 30}


In [45]:
# add()
s.add(60)
print("After add(60):", s)



After add(60): {50, 20, 40, 10, 60, 30}


In [46]:
# add multiple items using update()
s.update([70, 80])
print("After update([70,80]):", s)

After update([70,80]): {80, 50, 20, 70, 40, 10, 60, 30}


In [47]:
# update()
s.update([70, 80, 90])
print("After update([70,80,90]):", s)

After update([70,80,90]): {70, 10, 80, 20, 90, 30, 40, 50, 60}


In [32]:
# remove() — raises KeyError if missing
s.remove(90)
print("After remove(90):", s)

After remove(90): {70, 10, 80, 20, 30, 40, 50, 60}


In [33]:
s.remove(90)

KeyError: 90

In [34]:
# discard() — safe remove
print("\nBefore discard(999):", s)
s.discard(999)   # no error even though 999 doesn't exist
print("After discard(999):", s)


Before discard(999): {70, 10, 80, 20, 30, 40, 50, 60}
After discard(999): {70, 10, 80, 20, 30, 40, 50, 60}


In [48]:
# pop() — removes arbitrary element
print("\nBefore pop():", s)
popped = s.pop()
print(f"After pop(): {s}  | Popped: {popped}")


Before pop(): {70, 10, 80, 20, 90, 30, 40, 50, 60}
After pop(): {10, 80, 20, 90, 30, 40, 50, 60}  | Popped: 70


In [49]:
lis=[1,2,3,4]
lis.pop(1)
print(lis)

[1, 3, 4]


In [50]:
a=20
b=10
a&b

0

In [51]:
# ── Mathematical Set Operations ──────────────────────────────────
print("\n--- Set Operations ---")
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
print("A:", A)
print("B:", B)

print("\nA | B  (Union)               :", A | B)
print("A & B  (Intersection)        :", A & B)
print("A - B  (Difference A-B)      :", A - B)
print("B - A  (Difference B-A)      :", B - A)
print("A ^ B  (Symmetric Difference):", A ^ B)


--- Set Operations ---
A: {1, 2, 3, 4, 5}
B: {4, 5, 6, 7, 8}

A | B  (Union)               : {1, 2, 3, 4, 5, 6, 7, 8}
A & B  (Intersection)        : {4, 5}
A - B  (Difference A-B)      : {1, 2, 3}
B - A  (Difference B-A)      : {8, 6, 7}
A ^ B  (Symmetric Difference): {1, 2, 3, 6, 7, 8}


In [52]:


# Subset / Superset
C = {2, 3}
print("\nC:", C)
print("C.issubset(A)  :", C.issubset(A))     # C ⊆ A ?
print("A.issuperset(C):", A.issuperset(C))   # A ⊇ C ?
print("A.isdisjoint(B):", A.isdisjoint(B))   # No common elements?


C: {2, 3}
C.issubset(A)  : True
A.issuperset(C): True
A.isdisjoint(B): False


In [57]:
a={1,2,3}
b={4,5,6}

print(a.isdisjoint(b))

True


In [58]:
# ── 🎯 Practical Program: Course Enrollment Analyzer ─────────────

print("=" * 50)
print("       COURSE ENROLLMENT ANALYZER")
print("=" * 50)

python_students  = {"Alice", "Bob", "Charlie", "Diana", "Eve"}
java_students    = {"Bob", "Diana", "Frank", "Grace", "Heidi"}
ml_students      = {"Alice", "Eve", "Frank", "Ivan"}

print("Python students :", python_students)
print("Java students   :", java_students)
print("ML students     :", ml_students)

all_students = python_students | java_students | ml_students
print(f"\n👥 Total unique students: {len(all_students)}")
print("   Names:", all_students)

both_py_java = python_students & java_students
print(f"\n🔁 In both Python & Java  : {both_py_java}")

only_python = python_students - java_students - ml_students
print(f"🐍 Only Python (no other) : {only_python}")

all_three = python_students & java_students & ml_students
print(f"🌟 In all 3 courses       : {all_three if all_three else 'None'}")

in_only_one = set()
for s in all_students:
    count = (s in python_students) + (s in java_students) + (s in ml_students)
    if count == 1:
        in_only_one.add(s)
print(f"📚 In exactly 1 course    : {in_only_one}")

       COURSE ENROLLMENT ANALYZER
Python students : {'Charlie', 'Bob', 'Diana', 'Alice', 'Eve'}
Java students   : {'Bob', 'Diana', 'Heidi', 'Grace', 'Frank'}
ML students     : {'Alice', 'Frank', 'Ivan', 'Eve'}

👥 Total unique students: 9
   Names: {'Bob', 'Diana', 'Ivan', 'Eve', 'Frank', 'Charlie', 'Alice', 'Grace', 'Heidi'}

🔁 In both Python & Java  : {'Bob', 'Diana'}
🐍 Only Python (no other) : {'Charlie'}
🌟 In all 3 courses       : None
📚 In exactly 1 course    : {'Charlie', 'Grace', 'Heidi', 'Ivan'}


---
# 4. DICTIONARIES 📖

## What is a Dictionary?
A **Dictionary** stores data as **key-value pairs**. It is **ordered** (Python 3.7+), **mutable**, and keys must be **unique** and **immutable** (strings, numbers, tuples). Think of it like a real dictionary — you look up a word (key) to get its meaning (value).

### Key Characteristics:
| Property | Value |
|---|---|
| Ordered | ✅ Yes (Python 3.7+) |
| Mutable | ✅ Yes |
| Duplicate Keys | ❌ No |
| Duplicate Values | ✅ Yes |
| Syntax | `{ key: value }` |

---
## 4.1 Creating & Accessing Dictionaries

In [59]:
# ── Creating Dictionaries ────────────────────────────────────────

# Empty dictionary
empty_dict = {}
print("Empty dict:", empty_dict)

Empty dict: {}


In [79]:

# Standard creation
student = {
    "name"   : ["Alice", "Alice"],
    "age"    : 21,
    "grade"  : "A",
    "marks"  : 95.5,
    "passed" : True
}
print("Student dict:", student)

Student dict: {'name': ['Alice', 'Alice'], 'age': 21, 'grade': 'A', 'marks': 95.5, 'passed': True}


In [5]:
# Standard creation
student = {
    "name"   : "Alice",
    "age"    : 21,
    "grade"  : "A",
    "marks"  : 95.5,
    "passed" : True
}
print("Student dict:", student)

Student dict: {'name': 'Alice', 'age': 21, 'grade': 'A', 'marks': 95.5, 'passed': True}


In [65]:
std={3:'three',3:'3.0',2:'two',3:3}
print(std)

{3: 3, 2: 'two'}


In [ ]:
print(std)

In [66]:
# Using dict() constructor
config = dict(host="localhost", port=8080, debug=True)
print("Config:", config)

Config: {'host': 'localhost', 'port': 8080, 'debug': True}


In [67]:
std={local="localhost"}
print(std)

SyntaxError: invalid syntax (3328334730.py, line 1)

In [68]:
# Dictionary from two lists using zip()
keys   = ["x", "y", "z"]
values = [10, 20, 30]
coords = dict(zip(keys, values))
print("Coords:", coords)

Coords: {'x': 10, 'y': 20, 'z': 30}


In [69]:
# Dictionary from two lists using zip()
keys   = ["x", "y", "z"]
values = [10, 20]
coords = dict(zip(keys, values))
print("Coords:", coords)

Coords: {'x': 10, 'y': 20}


In [2]:
# Dictionary from two lists using zip()
keys   = ["x", "y"]
values = [(10,30), 20,40]
coords = dict(zip(keys, values))
print("Coords:", coords)

Coords: {'x': (10, 30), 'y': 20}


In [12]:
# Nested dictionary
school = {
    "Alice": {"math": 95, "science": 88},
    "Bob"  : {"math": 72, "science": 80},
}
print("Nested dict:", school)

# ── Accessing ────────────────────────────────────────────────────
print("\n--- Accessing ---")
print("student['name']      :", student["name"])
print("student.get('grade') :", student.get("grade"))
print("student.get('email') :", student.get("email", "Not Found"))  # default value

print("Nested access        :", school["Alice"]["math"])  # → 95

Nested dict: {'Alice': {'math': 95, 'science': 88}, 'Bob': {'math': 72, 'science': 80}}

--- Accessing ---
student['name']      : Alice
student.get('grade') : A
student.get('email') : Not Found
Nested access        : 95


In [13]:
student.get("grade","no grade assigned")

'A'

In [16]:
print(student.get("gender","not specified"))

not specified


In [11]:
print("student.get('email') :", student.get("email"))

student.get('email') : None


In [17]:
school["Alice"]["english"] = 90
print("After adding English score:", school)

After adding English score: {'Alice': {'math': 95, 'science': 88, 'english': 90}, 'Bob': {'math': 72, 'science': 80}}


In [18]:
print("Before modifying English score:", school)
school["Alice"]["english"] = 99
print("After modifying English score:", school)

Before modifying English score: {'Alice': {'math': 95, 'science': 88, 'english': 90}, 'Bob': {'math': 72, 'science': 80}}
After modifying English score: {'Alice': {'math': 95, 'science': 88, 'english': 99}, 'Bob': {'math': 72, 'science': 80}}


In [19]:
school["Alice"]


{'math': 95, 'science': 88, 'english': 99}

In [20]:
school["Bob"]

{'math': 72, 'science': 80}

In [21]:
school["Bob"]["english"]

KeyError: 'english'

In [22]:
school["Bob"].get("english")

## 4.2 All Dictionary Methods — Explained

| Method | Description |
|---|---|
| `get(key, default)` | Returns value for key; default if not found |
| `keys()` | Returns all keys |
| `values()` | Returns all values |
| `items()` | Returns all key-value pairs as tuples |
| `update(dict2)` | Merges dict2 into the dictionary |
| `pop(key)` | Removes key and returns its value |
| `popitem()` | Removes and returns the last inserted item |
| `setdefault(key, val)` | Returns value; sets it if key doesn't exist |
| `copy()` | Returns a shallow copy |
| `clear()` | Removes all key-value pairs |
| `fromkeys(keys, val)` | Creates dict from keys with a default value |

In [29]:
# ── All Dictionary Methods Demonstrated ─────────────────────────

d = {"name": ["Bob", "Alice"], "age": 25, "city": "Hyderabad", "score": 88}
print("Original:", d)



Original: {'name': ['Bob', 'Alice'], 'age': 25, 'city': 'Hyderabad', 'score': 88}


In [27]:
print(type(d.keys()))
keys=list(d.keys())
print("Keys as list:", keys)

<class 'dict_keys'>
Keys as list: ['name', 'age', 'city', 'score']


In [30]:
d.values()

dict_values([['Bob', 'Alice'], 25, 'Hyderabad', 88])

In [31]:
# keys(), values(), items()
print("\nkeys()  :", list(d.keys()))
print("values():", list(d.values()))
print("items() :", list(d.items()))




keys()  : ['name', 'age', 'city', 'score']
values(): [['Bob', 'Alice'], 25, 'Hyderabad', 88]
items() : [('name', ['Bob', 'Alice']), ('age', 25), ('city', 'Hyderabad'), ('score', 88)]


In [33]:
d.items()

dict_items([('name', ['Bob', 'Alice']), ('age', 25), ('city', 'Hyderabad'), ('score', 88)])

In [32]:
print(d)

{'name': ['Bob', 'Alice'], 'age': 25, 'city': 'Hyderabad', 'score': 88}


In [34]:
# get() with default
print("\nget('name')        :", d.get("name"))
print("get('email','N/A') :", d.get("email", "N/A"))




get('name')        : ['Bob', 'Alice']
get('email','N/A') : N/A


In [35]:
# update() — add/modify keys
d.update({"email": "bob@example.com", "age": 26})
print("\nAfter update():", d)




After update(): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'score': 88, 'email': 'bob@example.com'}


In [36]:
# setdefault() — set only if key doesn't exist
print("\nBefore setdefault():", d)
d.setdefault("country", "India")
print("After setdefault('country'):", d)
d.setdefault("name", "Changed!")   # won't change existing key
print("After setdefault():", d)




Before setdefault(): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'score': 88, 'email': 'bob@example.com'}
After setdefault('country'): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'score': 88, 'email': 'bob@example.com', 'country': 'India'}
After setdefault(): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'score': 88, 'email': 'bob@example.com', 'country': 'India'}


In [37]:
# pop() — remove specific key
removed = d.pop("score")
print(f"\nAfter pop('score'): {d} | Removed: {removed}")




After pop('score'): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com', 'country': 'India'} | Removed: 88


In [38]:
# popitem() — remove last inserted
last = d.popitem()
print(f"After popitem(): {d} | Removed: {last}")



After popitem(): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com'} | Removed: ('country', 'India')


In [40]:
dis={"name": "Bob", "age": 25, "city": "Hyderabad"}
print(dis)
dis.update({"gender": "Male"})
print(dis)
dis.popitem()
print(dis)

{'name': 'Bob', 'age': 25, 'city': 'Hyderabad'}
{'name': 'Bob', 'age': 25, 'city': 'Hyderabad', 'gender': 'Male'}
{'name': 'Bob', 'age': 25, 'city': 'Hyderabad'}


In [41]:
# copy()
d_copy = d.copy()
print("\nCopied dict:", d_copy)




Copied dict: {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com'}


In [42]:
dis=d
print(dis)

{'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com'}


In [43]:
d.update({"country": "India"})
print(d)
print(dis)
print(d_copy)

{'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com', 'country': 'India'}
{'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com', 'country': 'India'}
{'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com'}


In [44]:
# fromkeys()
template = dict.fromkeys(["math", "science", "english"], 0)
print("fromkeys():", template)



fromkeys(): {'math': 0, 'science': 0, 'english': 0}


In [45]:
# clear()
print("before clear():", d)
d.clear()
print("After clear():", d)

before clear(): {'name': ['Bob', 'Alice'], 'age': 26, 'city': 'Hyderabad', 'email': 'bob@example.com', 'country': 'India'}
After clear(): {}


In [ ]:
# ── 🎯 Practical Program: Inventory Management System ────────────

print("=" * 50)
print("       INVENTORY MANAGEMENT SYSTEM")
print("=" * 50)

inventory = {
    "Laptop"    : {"qty": 15, "price": 55000},
    "Mouse"     : {"qty": 50, "price": 800},
    "Keyboard"  : {"qty": 30, "price": 1500},
    "Monitor"   : {"qty": 8,  "price": 18000},
    "Headphones": {"qty": 20, "price": 3500},
}

print("\n📦 Current Inventory:")
print(f"  {'Item':<15} {'Qty':>5} {'Price (₹)':>12} {'Total Value':>15}")
print("-" * 50)
total_inventory_value = 0
for item, details in inventory.items():
    val = details["qty"] * details["price"]
    total_inventory_value += val
    print(f"  {item:<15} {details['qty']:>5} {details['price']:>12,} {val:>15,}")
print("-" * 50)
print(f"  {'TOTAL VALUE':<15} {'':>5} {'':>12} {total_inventory_value:>15,} ₹")

# Low stock alert
print("\n⚠️  Low Stock Alert (qty < 10):")
for item, details in inventory.items():
    if details["qty"] < 10:
        print(f"  ❗ {item}: only {details['qty']} left!")

# Add new item
inventory["Webcam"] = {"qty": 25, "price": 2500}
print("\n✅ Added Webcam to inventory.")
print("Updated item count:", len(inventory))

---
# 5. DIFFERENCES AMONG DATA STRUCTURES 📊

## Comprehensive Comparison Table

| Feature | List `[ ]` | Tuple `( )` | Set `{ }` | Dictionary `{k:v}` |
|---|---|---|---|---|
| **Ordered** | ✅ Yes | ✅ Yes | ❌ No | ✅ Yes (3.7+) |
| **Mutable** | ✅ Yes | ❌ No | ✅ Yes | ✅ Yes |
| **Duplicates** | ✅ Yes | ✅ Yes | ❌ No | Keys: ❌ / Values: ✅ |
| **Indexed** | ✅ Yes | ✅ Yes | ❌ No | By key |
| **Syntax** | `[1,2,3]` | `(1,2,3)` | `{1,2,3}` | `{'a':1}` |
| **Access** | By index | By index | Membership only | By key |
| **Speed** | Moderate | Fastest | Very Fast | Fast |
| **Use Case** | General purpose | Fixed data | Unique items | Key-value pairs |

In [ ]:
# ── Side-by-Side Comparison ───────────────────────────────────────

# Same data in all four structures
my_list  = [1, 2, 3, 2, 1]          # allows duplicates
my_tuple = (1, 2, 3, 2, 1)          # immutable
my_set   = {1, 2, 3, 2, 1}          # removes duplicates → {1,2,3}
my_dict  = {"a": 1, "b": 2, "c": 3} # key-value pairs

print("List  :", my_list)
print("Tuple :", my_tuple)
print("Set   :", my_set)    # notice: no duplicates, unordered
print("Dict  :", my_dict)

# Mutability test
my_list[0] = 99
print("\nList after edit [0]=99:", my_list)

try:
    my_tuple[0] = 99  # This will FAIL
except TypeError as e:
    print("Tuple modification error:", e)

# Memory comparison (tuples are more efficient)
import sys
lst = list(range(100))
tpl = tuple(range(100))
print(f"\nMemory — List of 100: {sys.getsizeof(lst)} bytes")
print(f"Memory — Tuple of 100: {sys.getsizeof(tpl)} bytes")
print("→ Tuples use less memory!")

# Speed test
import timeit
list_time  = timeit.timeit("[1,2,3,4,5]", number=1_000_000)
tuple_time = timeit.timeit("(1,2,3,4,5)", number=1_000_000)
print(f"\nCreation speed (1M times):")
print(f"  List  = {list_time:.4f}s")
print(f"  Tuple = {tuple_time:.4f}s")
print("→ Tuples are faster to create!")

---
# 6. APPLICATIONS OF DATA STRUCTURES 🚀

| Data Structure | Real-World Application |
|---|---|
| **List** | Shopping carts, to-do lists, student marks, playlists |
| **Tuple** | GPS coordinates, RGB colors, DB records, function returns |
| **Set** | Unique visitors, tags/hashtags, friend suggestions, spell-check |
| **Dictionary** | Student records, config settings, word frequency count, JSON data |

In [ ]:
# ── 🎯 Application 1: Word Frequency Counter (Dictionary) ─────────

text = "python is great python is easy python programming is fun"
words = text.split()
freq = {}
for word in words:
    freq[word] = freq.get(word, 0) + 1

print("Word Frequency:")
for word, count in sorted(freq.items(), key=lambda x: -x[1]):
    print(f"  '{word}': {'█' * count} ({count})")

print()

# ── 🎯 Application 2: Remove Duplicates from a List (Set) ─────────

raw_emails = ["a@x.com", "b@x.com", "a@x.com", "c@x.com", "b@x.com"]
unique_emails = list(set(raw_emails))
print("Original emails:", raw_emails)
print("Unique emails  :", unique_emails)

print()

# ── 🎯 Application 3: Shopping Cart (List + Dictionary) ───────────

catalog = {"Apple": 30, "Milk": 45, "Bread": 25, "Eggs": 60}
cart    = ["Apple", "Milk", "Apple", "Bread", "Eggs", "Milk"]

print("🛒 Shopping Cart:")
total = 0
bill = {}
for item in cart:
    bill[item] = bill.get(item, 0) + 1

for item, qty in bill.items():
    cost = qty * catalog[item]
    total += cost
    print(f"  {item:<8} x{qty}  ₹{catalog[item]:>4} each = ₹{cost}")
print(f"  {'─'*35}")
print(f"  Total: ₹{total}")

---
# 7. BRANCHING AND CONTROL LOOPS WITH DATA STRUCTURES 🔄

## 7.1 if / elif / else — Branching

Branching allows your program to make decisions based on conditions.

```
if condition:
    # runs when condition is True
elif another_condition:
    # runs when second condition is True
else:
    # runs when no condition is True
```

In [ ]:
# ── Branching with Data Structures ──────────────────────────────

# 1. if-elif-else with a List
print("--- Grade Classifier (List + if-elif-else) ---")
marks = [92, 45, 75, 55, 83, 38, 67]

for m in marks:
    if m >= 90:
        grade = "A+ (Outstanding)"
    elif m >= 75:
        grade = "A  (Excellent)"
    elif m >= 60:
        grade = "B  (Good)"
    elif m >= 50:
        grade = "C  (Average)"
    else:
        grade = "F  (Fail)"
    print(f"  Marks: {m:>3} → {grade}")

# 2. Branching with Dictionary
print("\n--- Menu System (Dictionary + if-elif) ---")
menu = {1: "Start Game", 2: "Load Game", 3: "Settings", 4: "Exit"}

choice = 2
if choice in menu:
    print(f"  You selected: {menu[choice]}")
else:
    print("  Invalid choice!")

# 3. Branching with Set (membership)
print("\n--- Access Control (Set + if) ---")
admins = {"alice", "bob", "carol"}
users  = ["alice", "dave", "bob", "eve"]

for user in users:
    if user in admins:
        print(f"  ✅ {user:<8} — Admin Access Granted")
    else:
        print(f"  ❌ {user:<8} — Regular User")

## 7.2 for / while Loops

| Loop | Use When |
|---|---|
| `for` | You know how many iterations (iterating over a collection) |
| `while` | You loop until a condition becomes False |

### Loop Control Statements:
| Statement | Effect |
|---|---|
| `break` | Exits the loop immediately |
| `continue` | Skips to the next iteration |
| `pass` | Does nothing (placeholder) |

In [ ]:
# ── Loops with Data Structures ───────────────────────────────────

# FOR loop over List
print("--- for loop over List ---")
fruits = ["apple", "banana", "cherry", "date"]
for i, fruit in enumerate(fruits, start=1):
    print(f"  {i}. {fruit.capitalize()}")

# FOR loop over Dictionary
print("\n--- for loop over Dictionary ---")
scores = {"Alice": 92, "Bob": 75, "Charlie": 88}
for name, score in scores.items():
    status = "PASS" if score >= 80 else "FAIL"
    print(f"  {name:<10}: {score}  [{status}]")

# FOR loop over Set
print("\n--- for loop over Set ---")
unique_tags = {"python", "data-science", "ml", "ai"}
for tag in sorted(unique_tags):
    print(f"  #{tag}")

# WHILE loop with List
print("\n--- while loop draining a stack ---")
stack = [10, 20, 30, 40, 50]
while stack:
    item = stack.pop()
    print(f"  Processed: {item}  | Remaining: {stack}")

# break and continue with List
print("\n--- break: stop at first multiple of 7 ---")
numbers = [3, 14, 9, 21, 8, 35, 6]
for n in numbers:
    if n % 7 == 0:
        print(f"  Found multiple of 7: {n} → stopping!")
        break
    print(f"  Checked: {n}")

print("\n--- continue: skip even numbers ---")
for n in range(1, 11):
    if n % 2 == 0:
        continue
    print(f"  Odd: {n}")

In [ ]:
# ── 🎯 Practical Program: Library Book Search System ──────────────

print("=" * 55)
print("          LIBRARY BOOK SEARCH SYSTEM")
print("=" * 55)

library = [
    {"title": "Python Crash Course",      "author": "Eric Matthes",   "available": True,  "genre": "Programming"},
    {"title": "Clean Code",               "author": "Robert Martin",  "available": False, "genre": "Programming"},
    {"title": "The Alchemist",            "author": "Paulo Coelho",   "available": True,  "genre": "Fiction"},
    {"title": "Atomic Habits",            "author": "James Clear",    "available": True,  "genre": "Self-Help"},
    {"title": "Deep Learning",            "author": "Goodfellow",     "available": False, "genre": "AI"},
    {"title": "Data Science Handbook",    "author": "Jake VanderPlas", "available": True, "genre": "Data Science"},
]

search_genre = "Programming"
print(f"\n🔍 Books in genre: '{search_genre}'")

found_any = False
for book in library:
    if book["genre"] != search_genre:
        continue   # skip non-matching genres
    found_any = True
    status = "✅ Available" if book["available"] else "❌ Checked Out"
    print(f"  📘 '{book['title']}' by {book['author']} — {status}")

if not found_any:
    print("  No books found in this genre.")

# Summary using loops and branching
available_count = sum(1 for b in library if b["available"])
genres = set(b["genre"] for b in library)
print(f"\n📊 Summary:")
print(f"  Total Books   : {len(library)}")
print(f"  Available     : {available_count}")
print(f"  Checked Out   : {len(library) - available_count}")
print(f"  Genres covered: {genres}")

In [6]:
# Matrix representation using nested lists
print("\n--- Matrix Representation (Nested Lists) ---")
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
for row in matrix:
    print("  ", row)



--- Matrix Representation (Nested Lists) ---
   [1, 2, 3]
   [4, 5, 6]
   [7, 8, 9]


---
# 8. MATRIX OPERATIONS USING NUMPY 🔢

## What is NumPy?
**NumPy** (Numerical Python) is the foundational library for scientific computing in Python. It provides:
- A powerful **N-dimensional array** object (`ndarray`)
- Fast mathematical operations (vectorized — no loops needed!)
- Linear algebra, Fourier transforms, random number generation

### Why NumPy over Python Lists?
| Feature | Python List | NumPy Array |
|---|---|---|
| Speed | Slow | ⚡ 100x faster |
| Memory | More | Less |
| Math ops | Manual loops | Vectorized |
| Data type | Mixed allowed | Fixed type |
| Dimensions | 1D only natively | Any dimension |

---
## 8.1 Creating Arrays & Matrices

In [9]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


In [8]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [10]:
arr=np.array(44)
print(arr)
print(type(arr))

44
<class 'numpy.ndarray'>


In [12]:
arr=np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
arr=np.array((1,2,3))
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [14]:
# 2D array (Matrix)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("\n2D Matrix (3x3):\n", A)
print("Shape:", A.shape)


2D Matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [16]:
# Special arrays
zeros = np.zeros((3, 3))
ones  = np.ones((2, 4))
eye   = np.eye(3)           # Identity matrix
rand  = np.random.randint(1, 10, size=(3, 3))  # Random ints 1-9

print("\nZeros (3x3):\n", zeros)
print("\nOnes  (2x4):\n", ones)
print("\nIdentity (3x3):\n", eye)
print("\nRandom (3x3):\n", rand)


Zeros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones  (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random (3x3):
 [[3 5 5]
 [4 2 6]
 [4 4 6]]


In [ ]:


# ── Creating Arrays ──────────────────────────────────────────────
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:




#0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

arr = np.array(42)

print(arr)

# 1D array
a = np.array([1, 2, 3, 4, 5])
print("\n1D Array:", a)
print("Shape:", a.shape, "| dtype:", a.dtype)








In [21]:
# arange and linspace
arr_range = np.arange(0, 20, 2)          # 0 to 18, step 2
arr_lin   = np.linspace(0, 1, 7)          # 5 evenly spaced values
print("\narange(0,20,2) :", arr_range)
print("linspace(0,1,5):", arr_lin)


arange(0,20,2) : [ 0  2  4  6  8 10 12 14 16 18]
linspace(0,1,5): [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [19]:
arr=np.arange(0,11,0.2)
print(arr)

[ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8]


## Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.



In [5]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 8.2 Array Indexing & Slicing

In [ ]:
# ── NumPy Indexing & Slicing ─────────────────────────────────────

M = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print("Matrix M:\n", M)

# Single element
print("\nM[0,0]  :", M[0, 0])    # top-left = 10
print("M[1,2]  :", M[1, 2])    # row 1, col 2 = 60
print("M[-1,-1]:", M[-1, -1])  # bottom-right = 90

# Row and column slices
print("\nFirst row    M[0,:]  :", M[0, :])
print("Last row     M[-1,:] :", M[-1, :])
print("First column M[:,0]  :", M[:, 0])
print("Last column  M[:,-1] :", M[:, -1])

# Sub-matrix
print("\nTop-left 2x2 M[:2,:2]:\n", M[:2, :2])
print("Bottom-right 2x2 M[1:,1:]:\n", M[1:, 1:])

# Boolean indexing
print("\nElements > 50:", M[M > 50])
print("Elements even :", M[M % 20 == 0])

In [ ]:
#Without Vectorization (using a loop)

import numpy as np

a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]

c = []
for i in range(len(a)):
    c.append(a[i] + b[i])

print(c)

In [2]:
#With Vectorization (NumPy)
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

c = a + b

print(c)

[11 22 33 44 55]


In [4]:
result = []
for x in [1, 2, 3, 4]:
    result.append(x * 2)

print(result)
print(type(result))

arr = np.array([1, 2, 3, 4])
result = arr * 2
print(result)
print(type(result))

[2, 4, 6, 8]
<class 'list'>
[2 4 6 8]
<class 'numpy.ndarray'>


### Why is Vectorization Faster?

1. Operations are executed in optimized C code.
2. Less Python interpreter overhead.
3. Better use of CPU cache and memory.
4. Many operations can leverage low-level optimizations.

### Simple Definition

Vectorization in NumPy is the technique of applying an operation to an entire array at once, without writing explicit Python loops, making the code shorter, cleaner, and faster.

## 8.3 Element-wise & Matrix Arithmetic

In [ ]:
# ── Element-wise Arithmetic ──────────────────────────────────────

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A:\n", A)
print("B:\n", B)

print("\nA + B  (element-wise add):\n",  A + B)
print("A - B  (element-wise sub):\n",  A - B)
print("A * B  (element-wise mul):\n",  A * B)
print("A / B  (element-wise div):\n",  A / B)
print("A ** 2 (element-wise power):\n", A ** 2)

# Scalar operations
print("\nA + 10 (scalar add):\n", A + 10)
print("A * 3  (scalar mul):\n", A * 3)

# Useful aggregate functions
C = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("\nMatrix C:\n", C)
print("sum()      :", C.sum())
print("sum(axis=0):", C.sum(axis=0))   # column sums
print("sum(axis=1):", C.sum(axis=1))   # row sums
print("mean()     :", C.mean())
print("std()      :", round(C.std(), 4))
print("min(), max():", C.min(), C.max())
print("argmax()   :", C.argmax())       # flat index of max

## 8.4 Linear Algebra Operations

In [ ]:
# ── Linear Algebra with NumPy ────────────────────────────────────

A = np.array([[2, 1], [5, 3]])
B = np.array([[1, 0], [2, 1]])

print("A:\n", A)
print("B:\n", B)

# Matrix multiplication (dot product)
print("\nMatrix Multiplication A @ B:\n", A @ B)
print("(same as np.dot(A, B)):\n", np.dot(A, B))

# Transpose
print("\nTranspose of A (A.T):\n", A.T)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# Inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)
print("Verify A @ inv(A) ≈ I:\n", np.round(A @ inv_A, 10))

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues :", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Solving linear equations: Ax = b
# 2x + y = 5
# 5x + 3y = 13
b = np.array([5, 13])
x = np.linalg.solve(A, b)
print("\nSolving Ax=b where b=[5,13]:")
print("x =", x)   # should be x=2, y=1
print("Verification A@x:", A @ x)

## 8.5 Reshaping & Stacking

In [ ]:
# ── Reshape, Stack, Split ────────────────────────────────────────

a = np.arange(1, 13)   # [1..12]
print("Original:", a)

# reshape()
m = a.reshape(3, 4)    # 3 rows, 4 columns
print("\nreshaped to (3,4):\n", m)

m2 = a.reshape(2, 2, 3)  # 3D tensor
print("\nreshaped to (2,2,3):\n", m2)

# flatten() — back to 1D
flat = m.flatten()
print("\nflattened:", flat)

# Stacking
r1 = np.array([1, 2, 3])
r2 = np.array([4, 5, 6])

vstacked = np.vstack([r1, r2])   # vertical stack (rows)
hstacked = np.hstack([r1, r2])   # horizontal stack

print("\nvstack:\n", vstacked)
print("hstack:", hstacked)

# Splitting
splits = np.split(np.arange(12), 3)   # split into 3 equal parts
print("\nSplit into 3 parts:", splits)

In [ ]:
# ── 🎯 Practical Program: Student Marks Matrix Analysis ───────────

print("=" * 60)
print("       STUDENT EXAM MARKS — MATRIX ANALYSIS")
print("=" * 60)

import numpy as np

students = ["Alice", "Bob", "Charlie", "Diana", "Eve"]
subjects = ["Math", "Physics", "Chemistry", "English", "CS"]

# Marks matrix: rows = students, cols = subjects
marks = np.array([
    [88, 92, 79, 85, 95],   # Alice
    [72, 68, 75, 80, 70],   # Bob
    [95, 98, 92, 88, 99],   # Charlie
    [60, 55, 62, 70, 58],   # Diana
    [84, 79, 88, 91, 87],   # Eve
])

print(f"\n{'Student':<12}", end="")
for s in subjects:
    print(f"{s:>10}", end="")
print(f"{'Total':>10} {'Avg':>8} {'Grade':>8}")
print("-" * 75)

totals = marks.sum(axis=1)
avgs   = marks.mean(axis=1)

for i, student in enumerate(students):
    row = marks[i]
    avg = avgs[i]
    grade = "A+" if avg>=90 else "A" if avg>=80 else "B" if avg>=70 else "C" if avg>=60 else "F"
    print(f"{student:<12}", end="")
    for m in row:
        print(f"{m:>10}", end="")
    print(f"{totals[i]:>10} {avg:>8.1f} {grade:>8}")

print("-" * 75)

# Subject-wise statistics
print("\n📊 Subject-wise Statistics:")
col_avg = marks.mean(axis=0)
col_max = marks.max(axis=0)
col_min = marks.min(axis=0)

print(f"  {'Subject':<12} {'Avg':>8} {'Max':>8} {'Min':>8}")
for j, sub in enumerate(subjects):
    print(f"  {sub:<12} {col_avg[j]:>8.1f} {col_max[j]:>8} {col_min[j]:>8}")

# Topper
topper_idx = avgs.argmax()
print(f"\n🏆 Overall Topper: {students[topper_idx]} ({avgs[topper_idx]:.1f} avg)")

# Students below 70 average
below = [students[i] for i in range(len(students)) if avgs[i] < 70]
print(f"⚠️  Below 70 avg  : {below if below else 'None'}")

---
# 📝 Summary & Quick Reference

## Choose the Right Data Structure:

```
Do you need KEY-VALUE pairs?  ─── YES ──► Dictionary  {'key': value}
        │
        NO
        │
Do you need UNIQUE elements?  ─── YES ──► Set          {1, 2, 3}
        │
        NO
        │
Will data CHANGE?             ─── YES ──► List         [1, 2, 3]
        │
        NO
        │
                                          Tuple        (1, 2, 3)
```

## NumPy Cheat Sheet:

| Operation | Code |
|---|---|
| Create array | `np.array([1,2,3])` |
| Create matrix | `np.array([[1,2],[3,4]])` |
| Zeros / Ones | `np.zeros((m,n))` / `np.ones((m,n))` |
| Identity | `np.eye(n)` |
| Random | `np.random.randint(low, high, size)` |
| Matrix multiply | `A @ B` or `np.dot(A,B)` |
| Transpose | `A.T` |
| Inverse | `np.linalg.inv(A)` |
| Determinant | `np.linalg.det(A)` |
| Solve Ax=b | `np.linalg.solve(A, b)` |
| Reshape | `A.reshape(m, n)` |
| Row sums | `A.sum(axis=1)` |
| Col means | `A.mean(axis=0)` |

---
## 🎓 Practice Exercises

1. **List**: Write a program to find the second largest element in a list without sorting.
2. **Tuple**: Create a tuple of tuples representing a 3x3 tic-tac-toe board. Access cells by position.
3. **Set**: Given two sets of students who like cricket and football, find students who like both, only cricket, and neither.
4. **Dictionary**: Build a phone book that supports add, delete, search, and display-all operations.
5. **Loops**: Using a dictionary, count how many times each character appears in a string.
6. **NumPy**: Create a 5x5 random matrix, normalize it (values between 0 and 1), and find its rank.

---
*Notebook prepared for academic study. Run cells in order. Modify and experiment freely!* 🚀

In [ ]:
# ── 💡 Bonus: Exercise Solutions Starter Code ────────────────────

# Exercise 5: Character frequency counter
text = "python programming"
char_freq = {}
for ch in text:
    if ch != " ":
        char_freq[ch] = char_freq.get(ch, 0) + 1

print("Character Frequencies:")
for ch, freq in sorted(char_freq.items(), key=lambda x: -x[1]):
    print(f"  '{ch}': {'▮' * freq} ({freq})")

print()

# Exercise 6: Normalize a NumPy matrix
import numpy as np
M = np.random.randint(1, 100, size=(5, 5)).astype(float)
normalized = (M - M.min()) / (M.max() - M.min())
rank = np.linalg.matrix_rank(M)

print("Random 5x5 Matrix:\n", M)
print("\nNormalized (0 to 1):\n", np.round(normalized, 3))
print("\nMatrix Rank:", rank)

In [2]:
n=int(input("Enter number of tuples to create: "))
lst=[]
for i in range(n):
    a=int(input("Enter value for a: "))
    b=int(input("Enter value for b: "))
    c=int(input("Enter value for c: "))
    lst.append((a,b,c))
print(lst)

[(10, 20, 40), (40, 50, 10)]


In [22]:
t=eval(input("enter"))

In [24]:
print(type(t))

<class 'int'>


In [25]:
s = {1, True, 2}

print(len(s))


2


In [26]:
print(s)

{1, 2}


In [27]:
d = {1:"A", True:"B"}

print(len(d), d[1])


1 B


In [28]:
print(d)

{1: 'B'}


In [29]:
pairs = [(10,20,40),(40,50,60),(70,80,90)]
result = [t[:-1]+(100,) for t in pairs]
print(result)


[(10, 20, 100), (40, 50, 100), (70, 80, 100)]


In [1]:
k=list(map(int, input().split()))

In [2]:
print(k)

[10, 20, 30]


In [3]:
m=input().split()
print(m)


['hai', 'how', 'are']
